PCI: dwc: rcar-gen5: Update to fix style issues reported by checkpatch
Fix coding style error flag by checkpatch.pl script:
ERROR: trailing whitespace
+^I}^I$
ERROR: code indent should use tabs where possible
+        if (ret < 0) {$

Signed-off-by: Thanh Le <thanh.le.wm@bp.renesas.com>