ASoC: rsnd: Fix build error when !CONFIG_PM_SLEEP
Building commit fa81b99ef6d9 ("ASoC: rsnd: Add emtpy suspend/resume
handlers") with CONFIG_PM_SLEEP disabled fails with

sound/soc/sh/rcar/core.c:1253:20: error: 'NUL' undeclared here (not in a function)
 #define DEV_PM_OPS NUL
                    ^
sound/soc/sh/rcar/core.c:1259:9: note: in expansion of macro 'DEV_PM_OPS'
   .pm = DEV_PM_OPS,
         ^
This patch fixes this by renaming correctly.

Signed-off-by: Dirk Behme <dirk.behme@de.bosch.com>
Signed-off-by: Takeshi Kihara <takeshi.kihara.df@renesas.com>