CPI: SPCR: Add missing opening brace
drivers/acpi/spcr.c: In function 'parse_spcr':
drivers/acpi/spcr.c:165:3: error: label 'done' used but not defined
   goto done;
   ^
drivers/acpi/spcr.c: At top level:
drivers/acpi/spcr.c:201:4: error: expected identifier or '(' before 'else'
  } else {
    ^
drivers/acpi/spcr.c:206:9: error: expected declaration specifiers or '...' before string constant
  pr_info("console: %s\n", opts);
         ^
drivers/acpi/spcr.c:206:52: error: unknown type name 'opts'
  pr_info("console: %s\n", opts);
                                                    ^
drivers/acpi/spcr.c:208:2: error: expected identifier or '(' before 'if'
  if (earlycon)
  ^
drivers/acpi/spcr.c:211:2: warning: data definition has no type or storage class
  err = add_preferred_console(uart, 0, opts + strlen(uart) + 1);
  ^
drivers/acpi/spcr.c:211:2: error: type defaults to 'int' in declaration of 'err' [-Werror=implicit-int]
drivers/acpi/spcr.c:211:30: error: 'uart' undeclared here (not in a function)
  err = add_preferred_console(uart, 0, opts + strlen(uart) + 1);
                              ^
drivers/acpi/spcr.c:211:39: error: 'opts' undeclared here (not in a function)
  err = add_preferred_console(uart, 0, opts + strlen(uart) + 1);
                                       ^
drivers/acpi/spcr.c:213:5: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token
 done:
     ^
drivers/acpi/spcr.c:215:2: error: expected identifier or '(' before 'return'
  return err;
  ^
drivers/acpi/spcr.c:216:1: error: expected identifier or '(' before '}' token
 }
 ^
drivers/acpi/spcr.c: In function 'parse_spcr':
drivers/acpi/spcr.c:201:2: warning: control reaches end of non-void function [-Wreturn-type]
  } else {
  ^

Fixes: fd46b1aebee729fb ("ACPI: SPCR: work around clock issue on xgene UART")
Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>