arm64: dts: Makefile: Comment out compiling of dtbo
Get the following error in Kernel v5.10, so This patch
will temporarily comment out the compilation of dtbo.

FATAL ERROR: Unknown output format "dtbo"
scripts/Makefile.lib:334: recipe for target
'arch/arm64/boot/dts/renesas/ulcb-kf-cn11.dtbo' failed

Signed-off-by: Koji Matsuoka <koji.matsuoka.xm@renesas.com>