iommu/ipmmu-vmsa: Convert to iommu_register_instance()
drivers/iommu/ipmmu-vmsa.c: In function 'ipmmu_vmsa_iommu_of_setup':
drivers/iommu/ipmmu-vmsa.c:1298:2: error: implicit declaration of
function 'of_iommu_set_ops' [-Werror=implicit-function-declaration]
  of_iommu_set_ops(np, (struct iommu_ops *)ops);
  ^

Cfr. commit 65e251a4634c5644 ("iommu: Drop the of_iommu_{set/get}_ops()
interface").

Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>