i2c: Fix kerneldoc and exported symbol for i2c_release_dma_bounce_buf()
drivers/i2c/i2c-core-base.c:2310:15: error: 'i2c_release_bounce_buf' undeclared here (not in a function)
 EXPORT_SYMBOL_GPL(i2c_release_bounce_buf);

Fixes: 30cafb58f58d2ed1 ("i2c: add helpers to ease DMA handling")
Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>