media: i2c: adv748x-hdmi: Use DIV_ROUND_CLOSEST_ULL() for u64 dividend
On arm32:

    drivers/built-in.o: In function `adv748x_hdmi_set_pixelrate':
    :(.text+0x1b8b1c): undefined reference to `__aeabi_uldivmod'

v4l2_bt_timings.pixelclock is u64, so it should be divided using
DIV_ROUND_CLOSEST_ULL() instead of DIV_ROUND_CLOSEST().

Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>