net: ethernet: renesas: rcar_gen4_ptp: Fix build error of R-Car Gen4 PTP
The rcar_gen4_ptp's functions are used by not only rswitch driver
but also rtsn one (and ravb on R-Car Gen4 SoCs too) so export the
necessary functions to be used by other loadable drivers.
Otherwise, the following build error happens if CONFIG_RTSN=m.

ERROR: modpost: "rcar_gen4_ptp_init"
[drivers/net/ethernet/renesas/rtsn.ko] undefined!
ERROR: modpost: "rcar_gen4_ptp_alloc"
[drivers/net/ethernet/renesas/rtsn.ko] undefined!

Additionally, separate rcar_gen4_ptp's configuration from
CONFIG_RENESAS_ETHERNET_SWITCH to do not add rtsn as
rswitch's dependency.

Signed-off-by: Phong Hoang <phong.hoang.wz@renesas.com>